// TODO:该目录为静态变量及静态方法库
export const TITLE = '学训宝后台'
export const CREATE = 'create'
export const ACTIVE_PATH = 'ACTIVE_PATH'
export const ACCESS_TOKEN = 'ACCESS_TOKEN'
export const icons = [
  'el-icon-upload',
  'el-icon-warning',
  'el-icon-date',
  'el-icon-delete',
  'el-icon-document',
  'el-icon-edit-outline',
  'el-icon-download',
  'el-icon-goods',
  'el-icon-search',
  'el-icon-info',
  'el-icon-message',
  'el-icon-edit',
  'el-icon-location',
  'el-icon-location-outline',
  'el-icon-menu',
  'el-icon-bell',
  'el-icon-mobile-phone',
  'el-icon-news',
  'el-icon-phone',
  'el-icon-phone-outline',
  'el-icon-picture',
  'el-icon-picture-outline',
  'el-icon-printer',
  'el-icon-question',
  'el-icon-share',
  'el-icon-star-on',
  'el-icon-setting',
  'el-icon-service',
  'el-icon-sold-out',
  'el-icon-star-off',
  'el-icon-tickets',
  'el-icon-zoom-in',
  'el-icon-time',
  'el-icon-view',
  'el-icon-upload2',
  'el-icon-zoom-out',
  'el-icon-my-group_fill',
  'el-icon-my-evaluate_fill',
  'el-icon-my-redpacket_fill',
  'el-icon-my-moneybagfill',
  'el-icon-my-skinfill',
  'el-icon-my-askfill',
  'el-icon-my-newshotfill',
  'el-icon-my-newsfill',
  'el-icon-my-medalfill',
  'el-icon-my-goodsnewfill',
  'el-icon-my-circlefill',
  'el-icon-my-formfill',
  'el-icon-my-recordfill',
  'el-icon-my-musicfill',
  'el-icon-my-emojiflashfill',
  'el-icon-my-emojifill',
  'el-icon-my-sponsorfill',
  'el-icon-my-profilefill',
  'el-icon-my-messagefill',
  'el-icon-my-goodsfill',
  'el-icon-my-crownfill',
  'el-icon-my-hotfill',
  'el-icon-my-tagfill',
  'el-icon-my-communityfill',
  'el-icon-my-commandfill',
  'el-icon-my-repairfill',
  'el-icon-my-servicefill',
  'el-icon-my-peoplefill',
  'el-icon-my-presentfill',
  'el-icon-my-markfill',
  'el-icon-my-paintfill',
  'el-icon-my-friendfill',
  'el-icon-my-newfill',
  'el-icon-my-creativefill',
  'el-icon-my-upstagefill',
  'el-icon-my-noticefill',
  'el-icon-my-countdownfill',
  'el-icon-my-mobilefill',
  'el-icon-my-lightfill',
  'el-icon-my-wefill',
  'el-icon-my-voicefill',
  'el-icon-my-rechargefill',
  'el-icon-my-appreciatefill',
  'el-icon-my-selectionfill',
  'el-icon-my-homefill',
  'el-icon-my-discoverfill',
  'el-icon-my-cartfill',
  'el-icon-my-shopfill',
  'el-icon-my-questionfill',
  'el-icon-my-likefill',
  'el-icon-my-commentfill',
  'el-icon-my-camerafill',
  'el-icon-my-locationfill',
]
export const TEACHER_LEVEL = 'TEACHER_LEVEL'
export const TEACHER_MENU = [{
  icon: '',
  name: '课程管理',
  url: '/teacher/course/video',
  children: [{
    icon: '',
    name: '视频课程',
    url: '/teacher/course/video',
  }, {
    icon: '',
    name: '直播课程',
    url: '/teacher/course/liveRadio',
  }, {
    icon: '',
    name: '线下课程',
    url: '/teacher/course/line',
  }],
}, {
  icon: '',
  name: '机构管理',
  url: '/teacher/institution/mine',
  children: [{
    icon: '',
    name: '我的机构',
    url: '/teacher/institution/mine',
  }, {
    icon: '',
    name: '机构教师',
    url: '/teacher/institution/teachers',
  }],
}, {
  icon: '',
  name: '直播工具下载',
  url: 'http://www.xuexunbao.com.cn/livetool.html',
}]
